const data = [
  //가게 하나
  {
    UUID: "", //입력X, 고유DB인식코드
    id: 1, //가게 고유번호, 1~ 순차적으로증가
    signDate: null, //수정X, 가게를 Restin에 등록한 날짜
    name: "호우수원",
    storeOwnerName: "김무개",
    accountHolder: "김무개",
    settlementAccount: "00-0000-0000-00",
    unitPrice: 0,
    location: "경기 수원시 팔달구 덕영대로895번길 20 1층 호우수원",
    subwayStation: {
      line1: ["수원", "온수"], // 카페 주변역이 여러개일 경우 여러개 다 입력
      line7: ["온수"], //온수처럼 여러호선이 곂칠 경우 line1, line7에 전부입력
    },
    gps: {
      Latitude: "", // 위도
      longitude: "", // 경도
    },
    distance: 287, // 네이버지도에서 하드넘버 가져오기 or 내위치(GPS)와 location 거리 계산값
    walkingTime: 2, // 분 단위 - distance값 나누기 75_소수점버림
    businessTime: {
      //null 이면 그날 휴무,
      // open : null 이면 close도 null이어야함
      monopen: "1200", //ex : "0930"
      monclose: "2200", //ex : "1800"
      monbreak: [],
      //ex : [["1300", "0200",],], 또는 [["1100", "0200",], ["1500", "0100",],],
      //["break시작시간", "break지속시간"] 위 사례에서는 13시부터 2시간동안 브레이크 타임
      tueopen: "1200",
      tueclose: "2200",
      tuebreak: [],
      wedopen: null,
      wedclose: null,
      wedbreak: [],
      thuopen: "1200",
      thuclose: "2200",
      thubreak: [],
      friopen: "1200",
      friclose: "2200",
      fribreak: [],
      satopen: "1200",
      satclose: "2200",
      satbreak: [],
      sunopen: "1200",
      sunclose: "2200",
      sunbreak: [],
    },
    BusinessState: true, // true = 기본값, false = 휴폐업 또는 일시정지
    BusinessAdminPause: ["1999.10.11", 1], //설정x 임시휴무일 ex : ["2024.10.11", 기간]
    ownerCall: "010-0000-0000",
    storeCall: "0507-1471-2079",
    insta: "@hou_suwon", // null 입력시 insta 없음
    wifiId: "HOU_5G", // null 입력시 wifi 없음
    wifiPw: "HOU1234567", // null 입력시 wifi 없음
    toiletManLocation: "출입문 오른쪽 건물",
    toiletManPw: "비밀번호 없음",
    toiletWomanLocation: "출입문 오른쪽 건물",
    toiletWomanPw: "비밀번호 없음",
  },
  //가게 둘부턴 여기서 작성
  {
    UUID: "", //입력X
    id: 2,
    signDate: null, //수정X
    name: "당산커피",
    storeOwnerName: "류지원",
    accountHolder: "류지원",
    settlementAccount: "539101-01-051753",
    unitPrice: 0,
    location: "서울 영등포구 당산로48길 2 지하 1층 1층",
    subwayStation: "당산",
    distance: 33,
    walkingTime: 1,
    businessTime: {
      monopen: "0800",
      monclose: "2100",
      monbreak: [],
      tueopen: "0800",
      tueclose: "2100",
      tuebreak: [],
      wedopen: "0800",
      wedclose: "2100",
      wedbreak: [],
      thuopen: "0800",
      thuclose: "2300",
      thubreak: [],
      friopen: "0800",
      friclose: "2300",
      fribreak: [],
      satopen: "0800",
      satclose: "2300",
      satbreak: [],
      sunopen: null,
      sunclose: null,
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-2122-6975",
    storeCall: "0507-0288-7038",
    insta: "@dangsan_coffee",
    wifiId: "-",
    wifiPw: "-",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 3,
    signDate: null, //수정X
    name: "모먼트커피",
    storeOwnerName: "다무개",
    accountHolder: "다무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "경기 수원시 팔달구 매산로 2 모먼트 커피",
    subwayStation: "수원",
    distance: 11,
    walkingTime: 1,
    businessTime: {
      monopen: "1100",
      monclose: "2100",
      monbreak: [],
      tueopen: "1100",
      tueclose: "2100",
      tuebreak: [],
      wedopen: "1100",
      wedclose: "2100",
      wedbreak: [],
      thuopen: "1100",
      thuclose: "2100",
      thubreak: [],
      friopen: "1100",
      friclose: "2100",
      fribreak: [],
      satopen: "1100",
      satclose: "2100",
      satbreak: [],
      sunopen: "1100",
      sunclose: "2100",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "0507-1492-1429",
    insta: "@our_moment_coffee",
    wifiId: "-",
    wifiPw: "-",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 4,
    signDate: null, //수정X
    name: "팔로미노",
    storeOwnerName: "라무개",
    accountHolder: "라무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "서울 서초구 나루터로 69",
    subwayStation: "신사",
    distance: 224,
    walkingTime: 2,
    businessTime: {
      monopen: "1000",
      monclose: "2100",
      monbreak: [],
      tueopen: "1000",
      tueclose: "2100",
      tuebreak: [],
      wedopen: "1000",
      wedclose: "2000",
      wedbreak: [],
      thuopen: "1000",
      thuclose: "2100",
      thubreak: [],
      friopen: "1000",
      friclose: "2100",
      fribreak: [],
      satopen: "1000",
      satclose: "2100",
      satbreak: [],
      sunopen: null,
      sunclose: null,
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "02-544-4443",
    insta: null,
    wifiId: "-",
    wifiPw: "-",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 5,
    signDate: null, //수정X
    name: "더커피마켓13",
    storeOwnerName: "마무개",
    accountHolder: "마무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "서울 성동구 금호로13길 3",
    subwayStation: "신금호",
    distance: 48,
    walkingTime: 1,
    businessTime: {
      monopen: null, //격주 월 휴무
      monclose: null,
      monbreak: [],
      tueopen: "0700",
      tueclose: "1900",
      tuebreak: [],
      wedopen: "0700",
      wedclose: "1900",
      wedbreak: [],
      thuopen: "0700",
      thuclose: "1900",
      thubreak: [],
      friopen: "0700",
      friclose: "1900",
      fribreak: [],
      satopen: "0800",
      satclose: "1800",
      satbreak: [],
      sunopen: "0800",
      sunclose: "1800",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "02-2237-3790",
    insta: "@the_coffee_market13",
    wifiId: "-",
    wifiPw: "-",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 6,
    signDate: null, //수정X
    name: "카페나임",
    storeOwnerName: "권미영",
    accountHolder: "권미영",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "서울 성동구 금호로13길 20 카페나임",
    subwayStation: "신금호",
    distance: 171,
    walkingTime: 2,
    businessTime: {
      monopen: null,
      monclose: null,
      monbreak: [],
      tueopen: "1000",
      tueclose: "1900",
      tuebreak: [],
      wedopen: "1000",
      wedclose: "1900",
      wedbreak: [],
      thuopen: "1000",
      thuclose: "1900",
      thubreak: [],
      friopen: "1000",
      friclose: "1900",
      fribreak: [],
      satopen: "1000",
      satclose: "1900",
      satbreak: [],
      sunopen: "0900",
      sunclose: "1900",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "0507-1406-8783",
    insta: "@cafe_naim",
    wifiId: "-",
    wifiPw: "-",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 7,
    signDate: null, //수정X
    name: "어질인",
    storeOwnerName: "사무개",
    accountHolder: "사무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "서울 성동구 마조로9길 18 1/2층 어질인",
    subwayStation: "왕십리",
    distance: 46,
    walkingTime: 1,
    businessTime: {
      monopen: "0900",
      monclose: "2300",
      monbreak: [],
      tueopen: "0900",
      tueclose: "2300",
      tuebreak: [],
      wedopen: "0900",
      wedclose: "2300",
      wedbreak: [],
      thuopen: "0900",
      thuclose: "2300",
      thubreak: [],
      friopen: "0900",
      friclose: "2300",
      fribreak: [],
      satopen: "0900",
      satclose: "2300",
      satbreak: [],
      sunopen: "0900",
      sunclose: "2300",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "0507-1441-9096",
    insta: "@_a_jil_in",
    wifiId: "injoo1204",
    wifiPw: "injoo1981",
    toiletManLocation: "2층 복도",
    toiletManPw: "비밀번호 없음",
    toiletWomanLocation: "오른쪽 상가 1층 복도",
    toiletWomanPw: "*1234*",
  },
  {
    UUID: "", //입력X
    id: 8,
    signDate: null, //수정X
    name: "꼬밍",
    storeOwnerName: "아무개",
    accountHolder: "아무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "서울 성동구 마조로11길 11-1 1층",
    subwayStation: "왕십리",
    distance: 142,
    walkingTime: 2,
    businessTime: {
      monopen: "1100",
      monclose: "2300",
      monbreak: [],
      tueopen: "1100",
      tueclose: "2300",
      tuebreak: [],
      wedopen: "1100",
      wedclose: "2300",
      wedbreak: [],
      thuopen: "1100",
      thuclose: "2300",
      thubreak: [],
      friopen: "1100",
      friclose: "2300",
      fribreak: [],
      satopen: "1100",
      satclose: "2300",
      satbreak: [],
      sunopen: "1100",
      sunclose: "2300",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "02-2295-4877",
    insta: "@cafe.komin",
    wifiId: "-",
    wifiPw: "-",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 9,
    signDate: null, //수정X
    name: "너디블루 버로우",
    storeOwnerName: "자무개",
    accountHolder: "자무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "서울 성동구 고산자로12길 15 너디블루 버로우",
    subwayStation: "왕십리",
    distance: 221,
    walkingTime: 2,
    businessTime: {
      monopen: "1200",
      monclose: "2200",
      monbreak: [],
      tueopen: "1200",
      tueclose: "2200",
      tuebreak: [],
      wedopen: "1200",
      wedclose: "2200",
      wedbreak: [],
      thuopen: "1200",
      thuclose: "2200",
      thubreak: [],
      friopen: "1200",
      friclose: "2200",
      fribreak: [],
      satopen: "1100",
      satclose: "2200",
      satbreak: [],
      sunopen: "1100",
      sunclose: "2200",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "02-2295-1310",
    insta: "@nerdyblue.burrow",
    wifiId: "burrow",
    wifiPw: "n1004100418",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
  {
    UUID: "", //입력X
    id: 10,
    signDate: null, //수정X
    name: "멜바",
    storeOwnerName: "차무개",
    accountHolder: "차무개",
    settlementAccount: "000000-00-000000",
    unitPrice: 0,
    location: "경기 군포시 공단로 296 1층",
    subwayStation: "금정",
    distance: 143,
    walkingTime: 2,
    businessTime: {
      monopen: "0900",
      monclose: "1800",
      monbreak: [],
      tueopen: "0900",
      tueclose: "1800",
      tuebreak: [],
      wedopen: null,
      wedclose: null,
      wedbreak: [],
      thuopen: "0900",
      thuclose: "1800",
      thubreak: [],
      friopen: "0900",
      friclose: "1800",
      fribreak: [],
      satopen: "1100",
      satclose: "1800",
      satbreak: [],
      sunopen: "1100",
      sunclose: "1800",
      sunbreak: [],
    },
    BusinessState: true,
    BusinessAdminPause: ["1999.10.11", 1], //설정x
    ownerCall: "010-0000-0000",
    storeCall: "0507-2093-3486",
    insta: "@patisserie.melba",
    wifiId: "melba",
    wifiPw: "melba1023",
    toiletManLocation: "-",
    toiletManPw: "-",
    toiletWomanLocation: "-",
    toiletWomanPw: "-",
  },
];
export default data;
